# Generated by Django 5.0.1 on 2026-02-11 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hosteler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hosteler_id', models.CharField(help_text='H2024001 format', max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('age', models.IntegerField()),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('occupation', models.CharField(default='student', max_length=50)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('bed', models.CharField(blank=True, max_length=10)),
                ('checkin_date', models.DateField(blank=True, null=True)),
                ('college', models.CharField(blank=True, max_length=200)),
                ('course', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('year', models.CharField(blank=True, max_length=10)),
                ('roll_no', models.CharField(blank=True, max_length=50)),
                ('student_id', models.CharField(blank=True, max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='hostelers/')),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('father_name', models.CharField(blank=True, max_length=200)),
                ('parent_phone', models.CharField(blank=True, max_length=15)),
                ('parent_address', models.TextField(blank=True)),
                ('emergency_name', models.CharField(blank=True, max_length=200)),
                ('emergency_phone', models.CharField(blank=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostelers', to='rooms.room')),
            ],
            options={
                'verbose_name': 'Hosteler',
                'verbose_name_plural': 'Hostelers',
                'db_table': 'hostelers',
                'ordering': ['-registration_date'],
            },
        ),
    ]
