# Generated by Django 5.0.1 on 2026-02-11 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outpass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_date', models.DateField()),
                ('return_date', models.DateField()),
                ('reason', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('issued_on', models.DateTimeField(auto_now_add=True)),
                ('approved_on', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=200)),
                ('warden_reply', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hosteler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outpasses', to='hostel.hosteler')),
            ],
            options={
                'verbose_name': 'Outpass',
                'verbose_name_plural': 'Outpasses',
                'db_table': 'outpasses',
                'ordering': ['-issued_on'],
            },
        ),
    ]
