# Generated by Django 5.0.1 on 2026-04-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outpass',
            name='parent_phone',
            field=models.CharField(blank=True, help_text='Phone number message was sent to', max_length=20),
        ),
        migrations.AddField(
            model_name='outpass',
            name='parent_response_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outpass',
            name='parent_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Parent Approved'), ('rejected', 'Parent Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='outpass',
            name='whatsapp_message_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
