# Generated by Django 5.0.1 on 2026-02-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('block', models.CharField(choices=[('a-block', 'A Block (Boys)'), ('b-block', 'B Block (Girls)')], max_length=20)),
                ('floor', models.CharField(choices=[('ground', 'Ground Floor'), ('first', 'First Floor'), ('second', 'Second Floor'), ('third', 'Third Floor')], max_length=20)),
                ('room_type', models.CharField(choices=[('ac', 'AC'), ('non-ac', 'Non-AC')], max_length=20)),
                ('bed_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('triple', 'Triple')], max_length=20)),
                ('total_beds', models.IntegerField()),
                ('available_beds', models.IntegerField()),
                ('room_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='rooms/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'db_table': 'rooms',
                'ordering': ['block', 'floor', 'room_number'],
            },
        ),
    ]
